/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
/**
 *
 * @author Asus
 */
public class pasien extends javax.swing.JPanel {

    /**
     * Creates new form pasien
     */
    public pasien() {
    initComponents();
    tampilData();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txttgl = new javax.swing.JTextField();
        txthp = new javax.swing.JTextField();
        jsimpan = new javax.swing.JButton();
        jubah = new javax.swing.JButton();
        jclear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jcari = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbjenis = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        jhapus1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(702, 643));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("PASIEN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID PASIEN");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("NAMA");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("TGL LAHIR");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("NO HP");

        txtid.addActionListener(this::txtidActionPerformed);

        txtnama.addActionListener(this::txtnamaActionPerformed);

        txttgl.addActionListener(this::txttglActionPerformed);

        txthp.addActionListener(this::txthpActionPerformed);

        jsimpan.setBackground(new java.awt.Color(0, 0, 0));
        jsimpan.setForeground(new java.awt.Color(255, 255, 255));
        jsimpan.setText("Simpan");
        jsimpan.setBorderPainted(false);
        jsimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jsimpan.setFocusPainted(false);
        jsimpan.addActionListener(this::jsimpanActionPerformed);

        jubah.setBackground(new java.awt.Color(0, 0, 0));
        jubah.setForeground(new java.awt.Color(255, 255, 255));
        jubah.setText("Ubah");
        jubah.setBorderPainted(false);
        jubah.setFocusPainted(false);
        jubah.addActionListener(this::jubahActionPerformed);

        jclear.setBackground(new java.awt.Color(0, 0, 0));
        jclear.setForeground(new java.awt.Color(255, 255, 255));
        jclear.setText("Clear");
        jclear.setBorderPainted(false);
        jclear.setFocusPainted(false);
        jclear.addActionListener(this::jclearActionPerformed);

        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setRowHeight(30);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jcari.addActionListener(this::jcariActionPerformed);

        jButton4.setText("cari");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Jenis kelamin");

        cbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - Laki", "Perempuan", " " }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Alamat");

        txtalamat.addActionListener(this::txtalamatActionPerformed);

        jhapus1.setBackground(new java.awt.Color(0, 0, 0));
        jhapus1.setForeground(new java.awt.Color(255, 255, 255));
        jhapus1.setText("Hapus");
        jhapus1.setBorderPainted(false);
        jhapus1.setFocusPainted(false);
        jhapus1.addActionListener(this::jhapus1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel5))
                                            .addGap(61, 61, 61))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(98, 98, 98)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtid, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                                                .addComponent(txtnama, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                                                .addComponent(txthp, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                                                .addComponent(cbjenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtalamat, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
                                            .addGap(44, 44, 44)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jubah)
                                                .addComponent(jsimpan)
                                                .addComponent(jclear)
                                                .addComponent(jhapus1)))
                                        .addComponent(txttgl, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcari, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsimpan))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jubah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jhapus1)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txthp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jclear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txttglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttglActionPerformed

    private void txthpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthpActionPerformed

    private void jubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jubahActionPerformed
                                 
    try {

        String sql = "UPDATE pasien SET nama=?, tanggal=?, jenis_kelamin=?, no_hp=?, alamat=? WHERE id_pasien=?";

        Connection conn = new koneksi().connect();
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, txtnama.getText());
        pst.setString(2, txttgl.getText());
        pst.setString(3, cbjenis.getSelectedItem().toString());
        pst.setString(4, txthp.getText());
        pst.setString(5, txtalamat.getText());
        pst.setString(6, txtid.getText());

        pst.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data berhasil diubah");
        tampilData();
    }catch (Exception e) {

        JOptionPane.showMessageDialog(null, "Gagal ubah : " + e);

         }
    }//GEN-LAST:event_jubahActionPerformed

    private void jcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcariActionPerformed

    private void jclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jclearActionPerformed
                                     
    txtid.setText("");
    txtnama.setText("");
    txttgl.setText("");
    txthp.setText("");
    txtalamat.setText("");

    cbjenis.setSelectedIndex(0);

    txtid.requestFocus();


    }//GEN-LAST:event_jclearActionPerformed

    private void jsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsimpanActionPerformed
        try {

        String sql = "INSERT INTO pasien(id_pasien,nama,tanggal,jenis_kelamin,no_hp,alamat) VALUES (?,?,?,?,?,?)";

        Connection conn = new koneksi().connect();
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, txtid.getText());
        pst.setString(2, txtnama.getText());
        pst.setString(3, txttgl.getText());
        pst.setString(4, cbjenis.getSelectedItem().toString());
        pst.setString(5, txthp.getText());
        pst.setString(6, txtalamat.getText());


        pst.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        tampilData();
    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, "Gagal simpan : " + e);

}
    }//GEN-LAST:event_jsimpanActionPerformed

    private void txtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatActionPerformed

    private void jhapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhapus1ActionPerformed
    try {

        String sql = "DELETE FROM pasien WHERE id_pasien=?";

        Connection conn = new koneksi().connect();
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, txtid.getText());

        pst.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data berhasil dihapus");

        tampilData();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, "Gagal hapus : " + e);

        }

    }//GEN-LAST:event_jhapus1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
                                        
    int baris = jTable2.rowAtPoint(evt.getPoint());

    String id = jTable2.getValueAt(baris, 0).toString();
    txtid.setText(id);

    String nama = jTable2.getValueAt(baris, 1).toString();
    txtnama.setText(nama);

    String tanggal = jTable2.getValueAt(baris, 2).toString();
    txttgl.setText(tanggal);

    String jk = jTable2.getValueAt(baris, 3).toString();
    cbjenis.setSelectedItem(jk);

    String hp = jTable2.getValueAt(baris, 4).toString();
    txthp.setText(hp);

    String alamat = jTable2.getValueAt(baris, 5).toString();
    txtalamat.setText(alamat);

    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID PASIEN");
    model.addColumn("NAMA");
    model.addColumn("TANGGAL");
    model.addColumn("JENIS KELAMIN");
    model.addColumn("NO HP");
    model.addColumn("ALAMAT");

    try {

        String sql = "SELECT * FROM pasien WHERE "
                + "id_pasien LIKE ? OR "
                + "nama LIKE ? OR "
                + "tanggal LIKE ? OR "
                + "jenis_kelamin LIKE ? OR "
                + "no_hp LIKE ? OR "
                + "alamat LIKE ?";

        Connection conn = new koneksi().connect();
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, "%" + jcari.getText() + "%");
        pst.setString(2, "%" + jcari.getText() + "%");
        pst.setString(3, "%" + jcari.getText() + "%");
        pst.setString(4, "%" + jcari.getText() + "%");
        pst.setString(5, "%" + jcari.getText() + "%");
        pst.setString(6, "%" + jcari.getText() + "%");

        ResultSet rs = pst.executeQuery();

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getString("id_pasien"),
                rs.getString("nama"),
                rs.getString("tanggal"),
                rs.getString("jenis_kelamin"),
                rs.getString("no_hp"),
                rs.getString("alamat")
            });

        }

        jTable2.setModel(model);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, "Gagal cari data : " + e);

    }

    }//GEN-LAST:event_jButton4ActionPerformed


private void tampilData() {

    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID PASIEN");
    model.addColumn("NAMA");
    model.addColumn("TANGGAL");
    model.addColumn("JENIS KELAMIN");
    model.addColumn("NO HP");
    model.addColumn("ALAMAT");

    try {

        String sql = "SELECT * FROM pasien";

        Connection conn = new koneksi().connect();
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getString("id_pasien"),
                rs.getString("nama"),
                rs.getString("tanggal"),
                rs.getString("jenis_kelamin"),
                rs.getString("no_hp"),
                rs.getString("alamat")
            });

        }

        jTable2.setModel(model);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, "Gagal tampil data : " + e);

    }

}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbjenis;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jcari;
    private javax.swing.JButton jclear;
    private javax.swing.JButton jhapus1;
    private javax.swing.JButton jsimpan;
    private javax.swing.JButton jubah;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txthp;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttgl;
    // End of variables declaration//GEN-END:variables
}
